# -*- coding: utf-8 -*-
"""Generate js/work-tests-data.js — 10 MCQ per work."""

import json
from pathlib import Path

TESTS = {
    "marvarid": [
        {"q": "Ruben dengizdan nima topdi?", "options": ["Oltin tangalar", "Marvarid", "Baliq", "Xazina"], "correct": 1},
        {"q": "Ruben marvaridni nima uchun sotmadi?", "options": ["Yo'qotib qo'ydi", "Do'stlari kamroq ko'ra boshladi", "Dengiz chig'anoqlarini o'rganmoqchi bo'ldi", "Onasi taqiqladi"], "correct": 2},
        {"q": "Ruben katta bo'lgach qanday kasb tanladi?", "options": ["Baliqchi", "Marvarid savdogari", "Dehqon", "Cho'pon"], "correct": 1},
        {"q": "Asarning asosiy qadriyati qaysi?", "options": ["Saxovat", "Yolg'on", "Hasad", "Dangasalik"], "correct": 0},
        {"q": "Ruben qaysi shaharni tark etdi?", "options": ["Dengiz yaqinidagi ona shahri", "Toshkent", "Samarqand", "Buxoro"], "correct": 0},
        {"q": "Marvarid savdosi qayerda bo'ladi?", "options": ["Kichik qishloqda", "Katta shaharlar", "Cho'lda", "Tog'da"], "correct": 1},
        {"q": "Ruben marvaridlarni qanday almashtirdi?", "options": ["Yangi marvaridga", "Oltinga", "Kitobga", "Uyga"], "correct": 0},
        {"q": "Asar qaysi janrga kiradi?", "options": ["Ertak", "She'r", "Masal", "Matn"], "correct": 0},
        {"q": "Ruben qayerlarga sayohat qildi?", "options": ["Marvarid topiladigan okean qirg'og'iga", "Cho'lga", "Tog'ga", "Bog'ga"], "correct": 0},
        {"q": "Asar saboqi nima haqida?", "options": ["Haqiqiy boylik saxovatdir", "Pul eng muhim", "O'yin yaxshi", "Yolg'on foydali"], "correct": 0},
    ],
    "temir-qoziq": [
        {"q": "Cho'pon yo'lda nima topdi?", "options": ["Hamyon oltin", "Kitob", "Qoziq", "Baliq"], "correct": 0},
        {"q": "Cho'pon topilgan molni nima qildi?", "options": ["Egasiga qaytardi", "O'zida qoldirdi", "Sotdi", "Yashirdi"], "correct": 0},
        {"q": "'Temir qoziq' nima ramzi?", "options": ["Boylik", "Halollik va to'g'ri yo'l", "Qo'rquv", "Dangasalik"], "correct": 1},
        {"q": "Ota boladan nima so'radi?", "options": ["Topilgan qoziqni o'zi olib borishi kerakligini", "Pul berishni", "Uy qurishni", "Kitob o'qishni"], "correct": 0},
        {"q": "Bola qayerdan o'tishi kerak edi?", "options": ["Darxon ari ko'prigidan", "Daryodan", "Tog'dan", "Shahardan"], "correct": 0},
        {"q": "Qoziq qayerdan topilgan?", "options": ["Qonqus anhori bo'yidagi daraxt tagidan", "Uy ichidan", "Bozordan", "Maktabdan"], "correct": 0},
        {"q": "Asarning asosiy qadriyati qaysi?", "options": ["Halollik", "Yolg'on", "Hasad", "Ochko'zlik"], "correct": 0},
        {"q": "Agar qoziq uydan chiqsa, nima bo'lishi mumkin?", "options": ["Ega o'g'ri deb gumon qiladi", "Hech narsa", "Mukofot beradi", "Bayram qiladi"], "correct": 0},
        {"q": "Asar qaysi janrga kiradi?", "options": ["Ertak", "She'r", "Hikoya", "Matn"], "correct": 0},
        {"q": "Halollik nima?", "options": ["To'g'ri yo'l va ishonch", "Yolg'on gap", "Ochko'zlik", "Qo'rqoqlik"], "correct": 0},
    ],
    "vatan-yoshlari": [
        {"q": "She'r muallifi kim?", "options": ["Zafar Diyor", "Mirtemir", "Quddus Muhammadiy", "Anvar Obidjon"], "correct": 0},
        {"q": "She'rda yoshlar nimaga chaqirilgan?", "options": ["Vatanni obod qilishga", "Dam olishga", "Sayohatga", "Faqat o'yinga"], "correct": 0},
        {"q": "She'rning asosiy g'oyasi nima?", "options": ["Vatanparvarlik", "Ochko'zlik", "Yalqovlik", "Hasad"], "correct": 0},
        {"q": "'Mardona-mardona tashlaylik qadam' qatorida nima aytilgan?", "options": ["Ozod va obod yurt bo'lsin", "Dam olaylik", "Uyga qaytamiz", "O'ynaymiz"], "correct": 0},
        {"q": "She'r qaysi sinf darsligida?", "options": ["4-sinf", "3-sinf", "5-sinf", "2-sinf"], "correct": 0},
        {"q": "Yoshlar nima deb ataladi?", "options": ["Vatan yoshlari", "Shahar yoshlari", "Dunyo yoshlari", "Tog' yoshlari"], "correct": 0},
        {"q": "She'rda bayroq haqida nima deyiladi?", "options": ["Abadiy porlasin", "Yashirilsin", "Yirtilsin", "Unutilsin"], "correct": 0},
        {"q": "She'r qaysi janrga kiradi?", "options": ["She'r", "Ertak", "Masal", "Hikoya"], "correct": 0},
        {"q": "Ota-bobolardan nima meros qolgan?", "options": ["Jasorat va shon", "Pul", "Uy", "Mashina"], "correct": 0},
        {"q": "She'r saboqi nima?", "options": ["Vatanni mehnat bilan obod qilish", "Sayohat qilish", "Uxlash", "Hasad qilish"], "correct": 0},
    ],
    "chin-va-yolgon": [
        {"q": "Masalda kim abadiy hurmat topdi?", "options": ["Chin (rost)", "Yolg'on", "Shoh", "Anqov"], "correct": 0},
        {"q": "Yolg'on nima qiladi?", "options": ["Yaxshilarni yo'ldan chalg'itadi", "Hammaga yordam beradi", "Rost gapiradi", "Kitob o'qiydi"], "correct": 0},
        {"q": "Chin nima bilan o'xshatilgan?", "options": ["Quyosh nuri va suv-havo", "Tosh", "Qor", "Tun"], "correct": 0},
        {"q": "Yolg'onning zaif tomoni nima?", "options": ["Tez fosh bo'lishi", "Doim yutishi", "Hurmat topishi", "Abadiy yashashi"], "correct": 0},
        {"q": "Masal qaysi janrga kiradi?", "options": ["Masal", "Ertak", "She'r", "Matn"], "correct": 0},
        {"q": "Asarning asosiy qadriyati qaysi?", "options": ["Halollik", "Yolg'on", "Hasad", "Dangasalik"], "correct": 0},
        {"q": "Chin qanday yuradi?", "options": ["Misoli lochin", "Yolg'on kabi", "Egri yo'l bilan", "Yashirin"], "correct": 0},
        {"q": "Yolg'on va Chin nima qiladi?", "options": ["Yo'lda uchrashadi", "Uyda yashaydi", "Daryoda suzadi", "Tog'da yashaydi"], "correct": 0},
        {"q": "Masal saboqi nima?", "options": ["Rostning yo'li yorug'", "Yolg'on yaxshi", "Chalg'ish kerak", "Jim turish kerak"], "correct": 0},
        {"q": "Yolg'on nima va'da qiladi?", "options": ["Ko'p va'da, lekin bajarilmaydi", "Hech narsa", "Doim rost", "Faqat yordam"], "correct": 0},
    ],
    "ona-qarzi": [
        {"q": "Rafiq oyidan nima so'radi?", "options": ["Mehnat haqi", "O'yin vaqti", "Kitob", "Mashina"], "correct": 0},
        {"q": "Ona o'z mehnati uchun qancha yozdi?", "options": ["Bepul", "Ko'p pul", "Yarim haq", "Ikki rupiya"], "correct": 0},
        {"q": "Rafiq qanday hujjat yozdi?", "options": ["Hisobot", "She'r", "Xat", "Ertak"], "correct": 0},
        {"q": "Asarning asosiy qadriyati qaysi?", "options": ["Ota-onaga hurmat", "Boylik", "Hasad", "Yolg'on"], "correct": 0},
        {"q": "Rafiq uyda qanday ishlarni sanadi?", "options": ["Ovqatlantirish, xarid, non keltirish", "Faqat o'ynash", "Sayohat", "Uyqu"], "correct": 0},
        {"q": "Ona mehri haqida nima deyiladi?", "options": ["Pul bilan o'lchanmaydi", "Arzon", "Keraksiz", "Qisqa muddatli"], "correct": 0},
        {"q": "Asar muallifi kim?", "options": ["Anvar Obidjon", "Mirtemir", "Zafar Diyor", "Ezop"], "correct": 0},
        {"q": "Asar qaysi sinf darsligida?", "options": ["4-sinf", "3-sinf", "5-sinf", "2-sinf"], "correct": 0},
        {"q": "Rafiq pul topganida nima qildi?", "options": ["Sanab ko'rdi", "Tashlab yubordi", "Yashirdi", "Bergan yo'q"], "correct": 0},
        {"q": "Hikoya saboqi nima?", "options": ["Ona mehrini qadrlash kerak", "Pul olish kerak", "Hisobot yozmaslik", "O'ynash kerak"], "correct": 0},
    ],
    "zardoz": [
        {"q": "Zardo'z nima bilan shug'ullanadi?", "options": ["Zar bilan kashta tikish", "Dehqonchilik", "Baliqchilik", "Temirchilik"], "correct": 0},
        {"q": "Usta hunarni nimaga o'xshatadi?", "options": ["Non va tuzga", "O'yinga", "Uyquga", "Pulga"], "correct": 0},
        {"q": "Asarning asosiy qadriyati qaysi?", "options": ["Mehnatsevarlik", "Dangasalik", "Yolg'on", "Hasad"], "correct": 0},
        {"q": "Hunarga nima orqali erishiladi?", "options": ["Tinimsiz mehnat va harakat", "O'yin", "Uyqu", "Yolg'on"], "correct": 0},
        {"q": "Bilim va hunarni kim tortib ololmaydi?", "options": ["Hech kim", "Faqat do'st", "Faqat ota", "Faqat o'qituvchi"], "correct": 0},
        {"q": "Asar muallifi kim?", "options": ["Mirkarim Osim", "Mirtemir", "Po'lat Mo'min", "Shukur Sa'dulla"], "correct": 0},
        {"q": "Asar qaysi janrga kiradi?", "options": ["Hikoya", "She'r", "Masal", "Ertak"], "correct": 0},
        {"q": "Inson qiyin vaziyatda nima qilishi mumkin?", "options": ["Hunarini ishlatib yengadi", "Tashvishlanmaydi", "Qochadi", "Yig'laydi"], "correct": 0},
        {"q": "Boylikni bir soniyada nima qilish mumkin?", "options": ["Yo'qotish", "Ikki barobar qilish", "Saqlash", "Oshirish"], "correct": 0},
        {"q": "Asar saboqi nima?", "options": ["Hunarni sevish va mehnat qilish", "Dangasalik", "O'yin", "Hasad"], "correct": 0},
    ],
    "karim-polvon": [
        {"q": "Karim qaysi milliy o'yin bilan shug'ullanadi?", "options": ["Uloq-ko'pkari", "Shaxmat", "Futbol", "Suzish"], "correct": 0},
        {"q": "Karim qanday ot bilan mashg'ul?", "options": ["Jiyron qashqa", "Ot emas", "Eshak", "Tuy"], "correct": 0},
        {"q": "Karimning eng yaxshi fazilati nima?", "options": ["Kamtarlik", "Maqtanchoqlik", "Qo'rqoqlik", "Hasad"], "correct": 0},
        {"q": "Asar muallifi kim?", "options": ["Xudoyberdi To'xtaboyev", "Mirtemir", "Po'lat Mo'min", "Zafar Diyor"], "correct": 0},
        {"q": "Haqiqiy polvonlik nimada?", "options": ["Odob va hurmatda", "Faqat kuchda", "Yolg'onda", "Hasadda"], "correct": 0},
        {"q": "Karim polvon nima qiladi?", "options": ["Otni parvarishlaydi", "Uy quradi", "Kitob sotadi", "Baliq tutadi"], "correct": 0},
        {"q": "Asarning qadriyati qaysi?", "options": ["Mas'uliyat", "Yolg'on", "Dangasalik", "Ochko'zlik"], "correct": 0},
        {"q": "Asar qaysi sinf darsligida?", "options": ["4-sinf", "3-sinf", "5-sinf", "2-sinf"], "correct": 0},
        {"q": "G'alaba yuki qanday?", "options": ["Og'ir", "Yengil", "Yo'q", "Arzon"], "correct": 0},
        {"q": "Asar saboqi nima?", "options": ["Kuch kamtarlik va hurmatda", "Faqat yutish", "Raqibni kamsitish", "Qo'rqish"], "correct": 0},
    ],
    "dustlik-kemasi": [
        {"q": "Bolalar nimani birgalikda yasashdi?", "options": ["Do'stlik kemasi", "Uy", "Mashina", "Ko'prik"], "correct": 0},
        {"q": "She'rning g'oyasi nima?", "options": ["Birlik va do'stlik", "Yakkalik", "Janjal", "Hasad"], "correct": 0},
        {"q": "Kema qachon suzadi?", "options": ["Hammasi birgalikda bo'lganda", "Yolg'iz", "Kechasi", "Hech qachon"], "correct": 0},
        {"q": "Asar muallifi kim?", "options": ["Quddus Muhammadiy", "Mirtemir", "Abdulla Oripov", "Zafar Diyor"], "correct": 0},
        {"q": "Asar qaysi janrga kiradi?", "options": ["She'r", "Ertak", "Masal", "Matn"], "correct": 0},
        {"q": "Asar qaysi sinf darsligida?", "options": ["3-sinf", "4-sinf", "5-sinf", "2-sinf"], "correct": 0},
        {"q": "Yolg'iz hech kim nima qila olmaydi?", "options": ["Katta ishni uddalay olmaydi", "O'qiy olmaydi", "Yuradi", "Gapiradi"], "correct": 0},
        {"q": "Do'stlik nima beradi?", "options": ["Kuch", "Hasad", "Yolg'on", "Qo'rquv"], "correct": 0},
        {"q": "Asarning qadriyati qaysi?", "options": ["Do'stlik", "Yolg'on", "Hasad", "Ochko'zlik"], "correct": 0},
        {"q": "She'r saboqi nima?", "options": ["Birlik har qanday to'siqni yengadi", "Yakka yurish yaxshi", "Janjal foydali", "Hasad kerak"], "correct": 0},
    ],
    "saxiy-dehqon": [
        {"q": "Dehqon hosilini nima qildi?", "options": ["Baham ko'rdi", "Yashirdi", "Tashladi", "Faqat sotdi"], "correct": 0},
        {"q": "Asarning asosiy qadriyati qaysi?", "options": ["Saxovat", "Hasad", "Yolg'on", "Ochko'zlik"], "correct": 0},
        {"q": "Qurg'oqchilikda nima bo'ldi?", "options": ["Yordam berganlar qo'llab-quvvatladi", "Hech kim yordam bermadi", "Dehqon ketdi", "Hosil ko'paydi"], "correct": 0},
        {"q": "Asar saboqi nima?", "options": ["Saxovat qaytadi", "Ochko'zlik foydali", "Yolg'iz yashash", "Hasad qilish"], "correct": 0},
        {"q": "Dehqon kim bilan baham ko'radi?", "options": ["Qo'shnilar va yo'lovchilar", "Hech kim", "Faqat oilasi", "Faqat boylar"], "correct": 0},
        {"q": "Asar qaysi janrga kiradi?", "options": ["Hikoya", "She'r", "Masal", "Ertak"], "correct": 0},
        {"q": "Asar qaysi sinf darsligida?", "options": ["3-sinf", "4-sinf", "5-sinf", "2-sinf"], "correct": 0},
        {"q": "Saxiyat nima?", "options": ["Beminnat berish", "Ochko'zlik", "Yolg'on", "Hasad"], "correct": 0},
        {"q": "Bergan qo'l qanday?", "options": ["Olgan qo'ldan ustun", "Past", "Keraksiz", "Xavfli"], "correct": 0},
        {"q": "Dehqon qanday inson?", "options": ["Mehnatkash va saxiy", "Dangasa", "Yolg'onchi", "Hasadchi"], "correct": 0},
    ],
    "adolatli-qozi": [
        {"q": "Qozi qanday hukm chiqardi?", "options": ["Adolatli", "Boyga yon bosib", "Kambag'alga yon bosib", "Hukm chiqarmadi"], "correct": 0},
        {"q": "Adolat nimaga o'xshatiladi?", "options": ["Teng tarozi", "Egri yo'l", "Yopiq eshik", "Bo'sh idish"], "correct": 0},
        {"q": "Asarning asosiy qadriyati qaysi?", "options": ["Adolat", "Yolg'on", "Hasad", "Ochko'zlik"], "correct": 0},
        {"q": "Qozi kimga yon bermaydi?", "options": ["Hech kimga", "Faqat boyga", "Faqat kambag'alga", "Faqat do'stiga"], "correct": 0},
        {"q": "Asar qaysi janrga kiradi?", "options": ["Ertak", "She'r", "Masal", "Matn"], "correct": 0},
        {"q": "Adolat nima?", "options": ["Haqqoniylik va insof", "Yolg'on", "Hasad", "Ochko'zlik"], "correct": 0},
        {"q": "Qozi nizoni qanday hal qiladi?", "options": ["Aql va adolat bilan", "Pul bilan", "Yolg'on bilan", "Hasad bilan"], "correct": 0},
        {"q": "Asar qaysi sinf darsligida?", "options": ["4-sinf", "3-sinf", "5-sinf", "2-sinf"], "correct": 0},
        {"q": "Tarozi ramzi nima?", "options": ["Adolat", "Boylik", "Yolg'on", "Hasad"], "correct": 0},
        {"q": "Asar saboqi nima?", "options": ["Adolat — tarozining ikki pallasini teng tutish", "Boyga yon berish", "Yolg'on gapirish", "Hasad qilish"], "correct": 0},
    ],
    "boburning-bolaligi": [
        {"q": "Bobur bolaligida nimani yaxshi ko'rardi?", "options": ["Kitob o'qish va she'r", "Faqat o'ynash", "Uxlash", "Janjal"], "correct": 0},
        {"q": "Bobur qaysi shaharda tantanada bo'lgan?", "options": ["Samarqand", "Toshkent", "Buxoro", "Andijon"], "correct": 0},
        {"q": "Sirli sandiq qanday ochiladi?", "options": ["Shahar nomlarini topish bilan", "Kalit bilan", "Tosh bilan", "Hech qanday"], "correct": 0},
        {"q": "Bobur qayerda tug'ilgan?", "options": ["Andijon", "Samarqand", "Toshkent", "Buxoro"], "correct": 0},
        {"q": "Asarning qadriyati qaysi?", "options": ["Vatanparvarlik", "Hasad", "Yolg'on", "Dangasalik"], "correct": 0},
        {"q": "Bobur keyinchalik kim bo'ldi?", "options": ["Shoir va davlat arbobi", "Savdogar", "Cho'pon", "Baliqchi"], "correct": 0},
        {"q": "Asar qaysi janrga kiradi?", "options": ["Matn", "She'r", "Ertak", "Masal"], "correct": 0},
        {"q": "Ona Boburga nima beradi?", "options": ["Mehr va o'pich", "Pul", "O'yinchoq", "Kitob emas"], "correct": 0},
        {"q": "Bobur qaysi shaharlar haqida gapiradi?", "options": ["Samarqand, Toshkent, Andijon", "Faqat bir shahar", "Chet el", "Dengiz"], "correct": 0},
        {"q": "Asar saboqi nima?", "options": ["Kitobxonlik va vatanparvarlik buyuklik olib keladi", "Faqat o'ynash", "Uxlash", "Hasad"], "correct": 0},
    ],
    "mehribon-qiz": [
        {"q": "Asarda qaysi qiz mehribon?", "options": ["Fotima", "Zuhra", "Ikkalasi", "Hech kim"], "correct": 0},
        {"q": "Buvisi qanday tanlov o'tkazdi?", "options": ["Sarishta qiz", "Eng tez yugurish", "Eng ko'p yig'ish", "Eng baland sakrash"], "correct": 0},
        {"q": "Zuhra nima qildi?", "options": ["Ko'p chiqindi yig'di", "Hech narsa qilmadi", "Kitob o'qidi", "Uxladi"], "correct": 0},
        {"q": "Tanlov g'olibi kim bo'ldi?", "options": ["Fotima", "Zuhra", "Buvisi", "Hech kim"], "correct": 0},
        {"q": "Asarning qadriyati qaysi?", "options": ["Mehribonlik", "Yolg'on", "Hasad", "Dangasalik"], "correct": 0},
        {"q": "Asar muallifi kim?", "options": ["Po'lat Mo'min", "Mirtemir", "Anvar Obidjon", "Zafar Diyor"], "correct": 0},
        {"q": "Zuhra qanday xulq-atvor ko'rsatadi?", "options": ["Ergash va tartibsiz", "Mehribon", "Juda o'qishga qiziq", "Jasur"], "correct": 0},
        {"q": "Asar qaysi sinf darsligida?", "options": ["3-sinf", "4-sinf", "5-sinf", "2-sinf"], "correct": 0},
        {"q": "Buvisi nima o'rgatmoqchi?", "options": ["Mehribonlik va tartib", "Yolg'on", "Hasad", "Dangasalik"], "correct": 0},
        {"q": "Asar saboqi nima?", "options": ["Kichik mehribon ishlar katta kuchga ega", "Chiqindi yig'ish yaxshi", "Ergashish kerak", "Hasad qilish"], "correct": 0},
    ],
    "halol-savdogar": [
        {"q": "Savdogarning asosiy fazilati nima?", "options": ["Halollik", "Aldamchilik", "Ochko'zlik", "Qo'rqoqlik"], "correct": 0},
        {"q": "Savdogar mijozni nima qilmaydi?", "options": ["Aldamaydi", "Xarid qilmaydi", "Gapirmaydi", "Savdo qilmaydi"], "correct": 0},
        {"q": "Halollik savdogarga nima berdi?", "options": ["Mijozlar ishonchi", "Zarar", "Yolg'izlik", "Jazo"], "correct": 0},
        {"q": "Savdogar tarozidan nima qilmaydi?", "options": ["Urmaydi", "Foydalanmaydi", "Sotmaydi", "Ko'rmaydi"], "correct": 0},
        {"q": "Asar qaysi janrga kiradi?", "options": ["Hikoya", "She'r", "Masal", "Ertak"], "correct": 0},
        {"q": "Asarning qadriyati qaysi?", "options": ["Halollik", "Yolg'on", "Hasad", "Dangasalik"], "correct": 0},
        {"q": "Avval xaridorlari qanday edi?", "options": ["Kam edi", "Juda ko'p", "Yo'q edi", "Faqat boylar"], "correct": 0},
        {"q": "Keyin odamlar nima qilishdi?", "options": ["Faqat undan xarid qilishdi", "Ketishdi", "Janjal qilishdi", "Yopishdi"], "correct": 0},
        {"q": "Asar qaysi sinf darsligida?", "options": ["4-sinf", "3-sinf", "5-sinf", "2-sinf"], "correct": 0},
        {"q": "Asar saboqi nima?", "options": ["Halol savdo barakali; ishonch oltindan qimmat", "Aldash foydali", "Ochko'zlik yaxshi", "Yolg'on kerak"], "correct": 0},
    ],
    "mehnat-bahosi": [
        {"q": "Kim qishga tayyorgarlik ko'rdi?", "options": ["Chumoli", "Tsikada", "Hech kim", "Ikkalasi ham"], "correct": 0},
        {"q": "Tsikada yozda nima qildi?", "options": ["Faqat kuyladi", "Don to'pladi", "Uy qurdi", "Sayohat qildi"], "correct": 0},
        {"q": "Qishda tsikada nima bo'ldi?", "options": ["Och qoldi", "Boy bo'ldi", "Sayohat qildi", "Uy oldi"], "correct": 0},
        {"q": "Asarning qadriyati qaysi?", "options": ["Mehnatsevarlik", "Dangasalik", "Yolg'on", "Hasad"], "correct": 0},
        {"q": "Chumoli tsikadaga nima qildi?", "options": ["Yordam berdi", "Haqorat qildi", "Quvib yubordi", "E'tibor bermadi"], "correct": 0},
        {"q": "Asar qaysi janrga kiradi?", "options": ["Masal", "She'r", "Ertak", "Matn"], "correct": 0},
        {"q": "Asar muallifi kim?", "options": ["Shukur Sa'dulla", "Mirtemir", "Ezop", "Po'lat Mo'min"], "correct": 0},
        {"q": "Chumoli nima to'pladi?", "options": ["Don", "Oltin", "Kitob", "Gul"], "correct": 0},
        {"q": "Asar qaysi sinf darsligida?", "options": ["3-sinf", "4-sinf", "5-sinf", "2-sinf"], "correct": 0},
        {"q": "Masal saboqi nima?", "options": ["Mehnat qilgan rohat ko'radi", "Dangasalik yaxshi", "Faqat kuylash kerak", "Uxlash kerak"], "correct": 0},
    ],
    "yolgonchi-cho'pon": [
        {"q": "Cho'pon nimani yolg'ondan baqirdi?", "options": ["'Bo'ri keldi!'", "'Yong'in!'", "'Suv toshdi!'", "'Mehmon keldi!'"], "correct": 0},
        {"q": "Nega odamlar oxirida ishonishmadi?", "options": ["Oldin yolg'on gapirgan edi", "Cho'pon yaxshi edi", "Bo'ri yo'q edi", "Kech bo'ldi"], "correct": 0},
        {"q": "Cho'pon nega yolg'on baqirdi?", "options": ["Zerikkanidan", "Mehnat uchun", "O'qish uchun", "Yordam uchun"], "correct": 0},
        {"q": "Asar qaysi janrga kiradi?", "options": ["Masal", "She'r", "Ertak", "Matn"], "correct": 0},
        {"q": "Asarning qadriyati qaysi?", "options": ["Halollik", "Yolg'on", "Hasad", "Ochko'zlik"], "correct": 0},
        {"q": "Haqiqatan bo'ri kelganda nima bo'ldi?", "options": ["Hech kim ishonmadi", "Hammasi yugurdi", "Cho'pon uxladi", "Bo'ri ketdi"], "correct": 0},
        {"q": "Asar muallifi/kaynaqi?", "options": ["Ezop masali", "Mirtemir", "Zafar Diyor", "Anvar Obidjon"], "correct": 0},
        {"q": "Yolg'on nima yo'qotadi?", "options": ["Ishonchni", "Kitobni", "Uyquni", "Ovqatni"], "correct": 0},
        {"q": "Asar qaysi sinf darsligida?", "options": ["3-sinf", "4-sinf", "5-sinf", "2-sinf"], "correct": 0},
        {"q": "Masal saboqi nima?", "options": ["Yolg'on ishonchni yo'qotadi", "Yolg'on foydali", "Baqirish kerak", "Zerikish yaxshi"], "correct": 0},
    ],
    "ota-nasihati": [
        {"q": "Ota o'g'illariga nima buyurdi?", "options": ["Novdani sindirish", "Uy qurish", "Sayohat", "O'yin"], "correct": 0},
        {"q": "Bog'langan novdalar nega sinmadi?", "options": ["Birlik kuchli", "Ular yumshoq", "Kalta edi", "Yangi edi"], "correct": 0},
        {"q": "Yolg'iz novda nima bo'ldi?", "options": ["Osongina sindi", "Sinmadi", "Gulladi", "O'smadi"], "correct": 0},
        {"q": "Otaning nasihati nima haqida?", "options": ["Ahillik va birlik", "Boylik", "O'yin", "Sayohat"], "correct": 0},
        {"q": "Asarning qadriyati qaysi?", "options": ["Ota-onaga hurmat", "Hasad", "Yolg'on", "Dangasalik"], "correct": 0},
        {"q": "Bog'bon nima ekdi?", "options": ["Ikkita bir xil nihol", "Bitta daraxt", "Gul", "Don"], "correct": 0},
        {"q": "Qaysi nihol chiroyli meva berdi?", "options": ["Shoxlari kesilgan", "Kesilmagan", "Ikkalasi ham", "Hech biri"], "correct": 0},
        {"q": "Asar qaysi janrga kiradi?", "options": ["Matn", "She'r", "Ertak", "Masal"], "correct": 0},
        {"q": "Asar qaysi sinf darsligida?", "options": ["4-sinf", "3-sinf", "5-sinf", "2-sinf"], "correct": 0},
        {"q": "Asar saboqi nima?", "options": ["Ota-ona nasihati qimmatli xazina", "Novda sindirish yaxshi", "Yakka yurish kerak", "Hasad qilish"], "correct": 0},
    ],
    "kitob-dosti": [
        {"q": "She'rda kitob nimaga o'xshatilgan?", "options": ["Sodiq do'stga", "Dushmanga", "Toshga", "O'yinchoqqa"], "correct": 0},
        {"q": "Kitob insonni qanday qiladi?", "options": ["Dono", "Dangasa", "G'amgin", "Yolg'iz"], "correct": 0},
        {"q": "Asar muallifi kim?", "options": ["Mirtemir", "Zafar Diyor", "Quddus Muhammadiy", "Anvar Obidjon"], "correct": 0},
        {"q": "Kitob nima beradi?", "options": ["Yangi bilim", "Faqat zerikish", "Yolg'on", "Hasad"], "correct": 0},
        {"q": "Asar qaysi janrga kiradi?", "options": ["She'r", "Ertak", "Masal", "Matn"], "correct": 0},
        {"q": "Asarning qadriyati qaysi?", "options": ["Do'stlik", "Yolg'on", "Hasad", "Ochko'zlik"], "correct": 0},
        {"q": "Kitob o'qigan bola nima qiladi?", "options": ["Dunyoni kengroq ko'radi", "Kam o'qiydi", "Uxladi", "Janjal qiladi"], "correct": 0},
        {"q": "Asar qaysi sinf darsligida?", "options": ["3-sinf", "4-sinf", "5-sinf", "2-sinf"], "correct": 0},
        {"q": "Kitob hech qachon nima qilmaydi?", "options": ["Aldamaydi", "O'qitmaydi", "Yordam bermaydi", "Bermaydi"], "correct": 0},
        {"q": "Asar saboqi nima?", "options": ["Kitob sodiq do'st va bilim xazinasi", "Kitob keraksiz", "O'yin yaxshi", "Uxlash kerak"], "correct": 0},
    ],
    "mardlik-qissasi": [
        {"q": "Asar qanday nom bilan ham taniladi?", "options": ["Mard bola", "Halol bola", "Dono bola", "Mehribon bola"], "correct": 0},
        {"q": "Asarning qadriyati qaysi?", "options": ["Mas'uliyat", "Yolg'on", "Dangasalik", "Hasad"], "correct": 0},
        {"q": "Mardlik nima?", "options": ["Qiyin daqiqada mas'uliyat olish", "Qo'rqish", "Yashirish", "Uxlash"], "correct": 0},
        {"q": "Asar qaysi janrga kiradi?", "options": ["Hikoya", "She'r", "Masal", "Ertak"], "correct": 0},
        {"q": "Asar qaysi sinf darsligida?", "options": ["4-sinf", "3-sinf", "5-sinf", "2-sinf"], "correct": 0},
        {"q": "Bolalar qayerda o'ynaydi?", "options": ["Maydonchada", "Daryoda", "Maktabda", "Bozorda"], "correct": 0},
        {"q": "Bolalar nima qilishadi?", "options": ["Orzularini aytishadi", "Janjal qilishadi", "Uxlashadi", "Yig'lashadi"], "correct": 0},
        {"q": "G'ani qanday orzu qiladi?", "options": ["Ustoz bo'lish", "Quruvchi", "Posbon", "Savdogar"], "correct": 0},
        {"q": "Muallif hikoyani qayerdan eshitadi?", "options": ["Bolalar gaplaridan", "Televizordan", "Kitobdan", "Radiodan"], "correct": 0},
        {"q": "Asar saboqi nima?", "options": ["Mas'uliyat va mardlik muhim", "Faqat o'ynash", "Orzu keraksiz", "Uxlash yaxshi"], "correct": 0},
    ],
    "navruz-bayrami": [
        {"q": "Navro'zda qaysi taom pishiriladi?", "options": ["Sumalak", "Osh", "Manti", "Somsa"], "correct": 0},
        {"q": "Navro'z qaysi faslda keladi?", "options": ["Bahorda", "Qishda", "Yozda", "Kuzda"], "correct": 0},
        {"q": "Asar muallifi kim?", "options": ["Quddus Muhammadiy", "Mirtemir", "Zafar Diyor", "Abdulla Oripov"], "correct": 0},
        {"q": "Navro'z nima bayrami?", "options": ["Yangilanish va ezgulik", "Qish", "Yoz", "Hasad"], "correct": 0},
        {"q": "Asar qaysi janrga kiradi?", "options": ["She'r", "Ertak", "Masal", "Matn"], "correct": 0},
        {"q": "Asarning qadriyati qaysi?", "options": ["Vatanparvarlik", "Yolg'on", "Hasad", "Dangasalik"], "correct": 0},
        {"q": "Navro'zda odamlar nima qiladi?", "options": ["Bir-birini tabriklaydi", "Janjal qiladi", "Uxlashadi", "Yig'ishadi"], "correct": 0},
        {"q": "Asar qaysi sinf darsligida?", "options": ["3-sinf", "4-sinf", "5-sinf", "2-sinf"], "correct": 0},
        {"q": "Tabiat Navro'zda nima qiladi?", "options": ["Uyg'onadi", "Uxlaydi", "Qor yog'adi", "Quriydi"], "correct": 0},
        {"q": "Asar saboqi nima?", "options": ["Navro'z — tabiat va qalbning yangilanishi", "Qish yaxshi", "Hasad kerak", "Yolg'on foydali"], "correct": 0},
    ],
    "oltin-tarvuz": [
        {"q": "Mehribon yigit qaldirg'ochga nima qildi?", "options": ["Qanotini davoladi", "Qafasga soldi", "Quvib yubordi", "E'tibor bermadi"], "correct": 0},
        {"q": "Qaldirg'och nima berdi?", "options": ["Tarvuz urug'i", "Oltin", "Kitob", "Non"], "correct": 0},
        {"q": "Ochko'z qo'shni nima qildi?", "options": ["Qaldirg'och qanotini sindirdi", "Yordam berdi", "Mehnat qildi", "Saxovat qildi"], "correct": 0},
        {"q": "Mehribon yigitning tarvuzidan nima chiqdi?", "options": ["Oltin", "Tosh", "Hech narsa", "Qor"], "correct": 0},
        {"q": "Ochko'z qo'shnining tarvuzidan nima chiqdi?", "options": ["Ziyon", "Oltin", "Gul", "Non"], "correct": 0},
        {"q": "Asarning qadriyati qaysi?", "options": ["Adolat", "Yolg'on", "Hasad", "Dangasalik"], "correct": 0},
        {"q": "Asar qaysi janrga kiradi?", "options": ["Ertak", "She'r", "Masal", "Matn"], "correct": 0},
        {"q": "Asar qaysi sinf darsligida?", "options": ["4-sinf", "3-sinf", "5-sinf", "2-sinf"], "correct": 0},
        {"q": "Ezgulik nima qiladi?", "options": ["Mukofotlanadi", "Jazolanadi", "Unutiladi", "Yo'qoladi"], "correct": 0},
        {"q": "Asar saboqi nima?", "options": ["Ezgulik qaytadi, yomonlik jazolanadi", "Ochko'zlik yaxshi", "Yolg'on foydali", "Hasad kerak"], "correct": 0},
    ],
}

assert len(TESTS) == 20, len(TESTS)
for wid, qs in TESTS.items():
    assert len(qs) == 10, f"{wid}: {len(qs)}"

out = Path(__file__).resolve().parents[1] / "js" / "work-tests-data.js"
lines = [
    "/* Har bir asar uchun 10 ta ko'p tanlovli savol — textbook-data.js bilan birga yuklanadi */",
    "const WORK_TESTS = " + json.dumps(TESTS, ensure_ascii=False, indent=2) + ";",
    "",
    "function applyWorkTests() {",
    "  if (typeof TEXTBOOK_WORKS === 'undefined') return;",
    "  TEXTBOOK_WORKS.forEach((w) => {",
    "    if (WORK_TESTS[w.id]) w.tests = WORK_TESTS[w.id];",
    "  });",
    "}",
    "",
    "applyWorkTests();",
    "",
    "if (typeof window !== 'undefined') {",
    "  window.WORK_TESTS = WORK_TESTS;",
    "  window.applyWorkTests = applyWorkTests;",
    "}",
    "",
]
out.write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {out} ({len(TESTS)} works, {sum(len(v) for v in TESTS.values())} questions)")
